---
  version: 2.1
  jobs:
    yaml_lint:
      docker:
        - image: opstree/docker:ansible-lint
      steps:
        - checkout
        - run: echo "YAMl lint safal hua"
    ansible_lint:
      docker:
        - image: opstree/docker:ansible-lint
      steps:
        - checkout
        - run: echo "Ansible lint safal hua"
  workflows:
    version: 2.1
    lint_tests:
      jobs:
        - yaml_lint
        - ansible_lint
...
  